# -*- coding: utf-8 -*-
"""Credit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14O8f-vN0yYsmzfwCztL_Ghsx84U8FIWm
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
from imblearn.over_sampling import RandomOverSampler
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier

data = pd.read_csv('cdd.csv')

X = data.drop('Class', axis=1)
y = data['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("NaN values in y_train:", np.isnan(y_train).sum())
y_train = y_train.to_numpy().reshape(-1, 1)  # Convert Series to 2D array
imputer = SimpleImputer(strategy='most_frequent')
y_train = imputer.fit_transform(y_train).ravel()  # Impute and flatten back to 1D

# Initialize Random Forest model
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
rf_classifier.fit(X_train, y_train)

# Predictions
y_pred = rf_classifier.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Random Forest Model Accuracy:", accuracy)

rf_classifier.fit(X_train, y_train)

models = {
    "Logistic Regression": LogisticRegression(solver='liblinear'),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "SVM": SVC(kernel='linear')
}

# Train and evaluate each model
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"{name} Accuracy: {accuracy:.4f}")

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

random_forest_model = RandomForestClassifier(random_state=42)
random_forest_model.fit(X_train, y_train)
y_pred_rf = random_forest_model.predict(X_test)

print("Random Forest Model:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_rf):.2f}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred_rf)}")
print(f"Classification Report:\n{classification_report(y_test, y_pred_rf)}")
print("-" * 50)

logistic_regression_model = LogisticRegression(random_state=42, max_iter=1000)
logistic_regression_model.fit(X_train_scaled, y_train)
y_pred_lr = logistic_regression_model.predict(X_test_scaled)

print("Logistic Regression Model:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_lr):.2f}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred_lr)}")
print(f"Classification Report:\n{classification_report(y_test, y_pred_lr)}")
print("-" * 50)

svm_model = SVC(random_state=42)
svm_model.fit(X_train_scaled, y_train)
y_pred_svm = svm_model.predict(X_test_scaled)

print("Support Vector Machine (SVM) Model:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_svm):.2f}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred_svm)}")
print(f"Classification Report:\n{classification_report(y_test, y_pred_svm)}")
print("-" * 50)

# Define features and target variable
X = data.drop(columns=['Class'])  # Features
y = data['Class']  # Target variable

# Apply Random Oversampling
ros = RandomOverSampler(random_state=42)
X_resampled, y_resampled = ros.fit_resample(X, y)

# Convert back to DataFrame for visualization
df_resampled = pd.DataFrame(X_resampled, columns=X.columns)
df_resampled['Class'] = y_resampled

# Plot the distribution
plt.figure(figsize=(8, 6))
sns.countplot(x=df_resampled["Class"], palette="muted")
plt.title("Distribution of Target Variable in Oversampled Training Set", fontsize=14)
plt.xlabel("Class (0: Non-Fraudulent, 1: Fraudulent)")
plt.ylabel("Count")
plt.xticks([0, 1], ["0", "1"])

# Show plot
plt.show()

knn_model = KNeighborsClassifier()
knn_model.fit(X_train_scaled, y_train)
y_pred_knn = knn_model.predict(X_test_scaled)

print("K-Nearest Neighbors (KNN) Model:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_knn):.2f}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred_knn)}")
print(f"Classification Report:\n{classification_report(y_test, y_pred_knn)}")
print("-" * 50)

features = ['V3', 'V4', 'V9', 'V10', 'V11', 'V12', 'V14', 'V16', 'V17', 'V18']


plt.figure(figsize=(12, 10))
for i, feature in enumerate(features):
    plt.subplot(4, 3, i + 1)
    sns.boxplot(x='Class', y=feature, data=data, palette="coolwarm")
    plt.title(f'Box plot of {feature}')

plt.tight_layout()
plt.suptitle("Box Plots for Features", fontsize=16)
plt.subplots_adjust(top=0.92)
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(12, 5))


sns.histplot(data['Time'], bins=50, kde=False, color="blue", ax=axes[0])
axes[0].set_title("Distribution of Time")
axes[0].set_xlabel("Time (in Seconds)")
axes[0].set_ylabel("Frequency")


sns.histplot(data['Amount'], bins=50, kde=False, color="green", ax=axes[1])
axes[1].set_title("Distribution of Amount")
axes[1].set_xlabel("Amount (in Currency)")
axes[1].set_ylabel("Frequency")


plt.tight_layout()
plt.show()

print("Please enter values for the features to predict the class:")
feature_names = X.columns.tolist()

corr_matrix = data.corr()


plt.figure(figsize=(12, 8))
sns.heatmap(corr_matrix, cmap="coolwarm", annot=False, fmt=".2f", linewidths=0.5, vmin=-1, vmax=1)
plt.title("Correlation Heatmap")
plt.show()

user_input = []
for feature in feature_names:
    value = float(input(f"Enter value for {feature}: "))
    user_input.append(value)

import numpy as np

print("\nPredictions for user input:")
user_input_array = np.array(user_input).reshape(1, -1)  # Convert to 2D array

print(f"Random Forest Prediction: {random_forest_model.predict(user_input_array)[0]}")
print(f"Logistic Regression Prediction: {logistic_regression_model.predict(user_input_array)[0]}")
print(f"SVM Prediction: {svm_model.predict(user_input_array)[0]}")
print(f"KNN Prediction: {knn_model.predict(user_input_array)[0]}")